create table product (
  id numeric generated by default as identity (start with 1, increment by 1),
  name varchar(200),
  description varchar(2000),
  price numeric(10,2),
  file_content varchar(500),
  primary key (id)
);
